#@ load("@ytt:data", "data")

#@ load("/lib/cmake.lib.yml", "cmake")
#@ load("/lib/fn_args.lib.yml", "mandatory")
#@ load("/lib/shell.lib.yml", "expand_args")

#@yaml/text-templated-strings
---
#@ def _configure_llvm(cmake_build_type=mandatory, cflags=mandatory, additional_cmake_options=mandatory, source_dir="$SOURCE_DIR"):
- |
  mkdir -p "$BUILD_DIR"
  cd "$BUILD_DIR";
  (@= cmake @) \
    "(@= source_dir @)/llvm" \
    -GNinja \
    -DCMAKE_BUILD_RPATH="\$ORIGIN/../lib:$ORCHESTRA_ROOT/lib" \
    -DCMAKE_INSTALL_RPATH="$RPATH_PLACEHOLDER/lib" \
    -DCMAKE_BUILD_TYPE="(@= cmake_build_type @)" \
    -DCMAKE_INSTALL_SO_NO_EXE=0 \
    -DCMAKE_EXE_LINKER_FLAGS="(@= data.values.use_old_glibc_ldflags @) (@= cflags @) (@= data.values.modern_linker_flags @)" \
    -DCMAKE_SHARED_LINKER_FLAGS="(@= data.values.use_old_glibc_ldflags @) (@= cflags @) (@= data.values.modern_linker_flags @)" \
    -DCMAKE_MODULE_LINKER_FLAGS="(@= data.values.use_old_glibc_ldflags @) (@= cflags @) (@= data.values.modern_linker_flags @)" \
    -DCMAKE_CXX_FLAGS="(@= data.values.use_old_glibc_cflags @) (@= cflags @)" \
    -DLLVM_TARGETS_TO_BUILD="X86;AMDGPU" \
    -DLLVM_ENABLE_DUMP=ON \
    -DLLVM_ENABLE_TERMINFO=OFF \
    -DLIBCXX_ENABLE_ABI_LINKER_SCRIPT=OFF \
    -DLLVM_ENABLE_Z3_SOLVER=OFF \
    (@= expand_args(additional_cmake_options) @) \
    -Wno-dev
#@ end

---

#@ def configure_llvm(**kwargs):
#@   return _configure_llvm(**kwargs)[0]
#@ end
